version: "2"
services: 
  node:
    image: "node:latest"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports: 
      - "8000:8000"
      - "8080:8080"
    expose:
      - "8000"
      - "8080"
    command: "npm run build"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"